modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"

[[mods]]
modId = "cobblemonspawncustom"
version = "0.0.1"
displayName = "Cobblemon Spawn Custom"
authors = "Yuri Celaschi"
description = '''
Mod para customizar os spawns dos Pok√©mon no Cobblemon.
'''

[[dependencies.cobblemonspawncustom]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="SERVER"

[[dependencies.cobblemonspawncustom]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="SERVER"

[[dependencies.cobblemonspawncustom]]
    modId = "cobblemon"
    mandatory = true
    versionRange = "[1.6.1,)"
    ordering = "AFTER"
    side = "SERVER"
